# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Maha Ahmed
tagline:          'Maha Ahmed'
description:      'Data science portfolio'
url:              http://amdmh.gitbub.io

author:
  name:           'Maha Ahmed'
  url:            https://amdmh.github.io

paginate:         2
google_analytics: 'UA-145826162-1'
emailme:          mailto:maha.ahmed@protonmail.com

gems:             [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap]

github:
  repo:           https://github.com/amdmh/amdmh.github.io/

tags:

github_username:  amdmh
linkedin_username: mahmd
