# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Maha Ahmed
tagline:          'Maha Ahmed'
description:      'Data science portfolio'
url:              http://amdmh.gitbub.io

author:
  name:           'Maha Ahmed'
  url:            https://amdmh.github.io

paginate:         2
google_analytics: 'UA-145826162-1'
emailme:           mailto:maha.ahmed@protonmail.com

# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: porfolio-2

plugins:             [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap]

github:
  repo:           https://github.com/amdmh/amdmh.github.io/

tags:

github_username:  amdmh
linkedin_username: mahmd
